spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: remote
        password: Sxr20010402
        url: jdbc:mysql://localhost:3306/paper_management

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:/mapper/*.xml

shiro:
    sessionManager:
        sessionIdCookieEnabled: true
    loginUrl: /api/user/login

